# .github/dependabot.yml
# This configuration file enables Dependabot to automatically check for dependency updates.
# For complete configuration options, please refer to:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"   # Replace with your package ecosystem (e.g., npm, maven, pip, gradle, docker, etc.)
    directory: "/"             # Specify the directory containing your package manifests
    schedule:
      interval: "weekly"       # Options include "daily", "weekly", "monthly"
      # day: "monday"          # (Optional) Specify the day of the week for weekly updates
    # Optionally, you can add further customizations:
    # allow:
    #   - dependency-type: "direct"  # Options: "direct", "indirect"
    # ignore:
    #   - dependency-name: "example-package"
    #     versions:
    #       - ">=1.0.0"
